AdminLTE1/Controllers/CMSController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using AdminLTE1.Models;
using AdminLTE1.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;

namespace AdminLTE1.Controllers
{
    public class CMSController : Controller
    {
        private readonly AddDbContext _context;
        private readonly IHostingEnvironment _hostEnvironment;

        public CMSController(AddDbContext context, IHostingEnvironment hostEnvironment)
        {
            _context = context;
            _hostEnvironment = hostEnvironment;
        }
        public IActionResult Index()
        {
            List<CMSItemsViewModel> lstmodel = new List<CMSItemsViewModel>();
            var models = _context.CMSItems.ToList();
            
            foreach (var item in models)
            {
                CMSItemsViewModel mvm = new CMSItemsViewModel();
                mvm.Id = item.Id;
                mvm.PageName = item.PageName;
                mvm.PageUrl = item.PageUrl;
                mvm.Description = item.Description;
                mvm.BannerImage = item.BannerImage;
                lstmodel.Add(mvm);
            }

            return View(lstmodel);
        }
        [HttpGet]
        public IActionResult CreatePage()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreatePage(CMSItemsViewModel model)
        {
            if (ModelState.IsValid)
            {
                var cmsModel = new CMSItems();
                cmsModel.PageName = model.PageName;
                cmsModel.PageUrl = model.PageUrl;
                cmsModel.Description = model.Description;
                if (model.BannerImageFile != null)
                {
                    string wwwRootPath = _hostEnvironment.WebRootPath;
                    string fileName = Path.GetFileNameWithoutExtension(model.BannerImageFile.FileName);
                    string extension = Path.GetExtension(model.BannerImageFile.FileName);
                    cmsModel.BannerImage = DateTime.Now.ToString("yymmssfff") + extension;


                    string path = Path.Combine(wwwRootPath, "Images", cmsModel.BannerImage);
                    var fileStream = new FileStream(path, FileMode.Create);
                    model.BannerImageFile.CopyTo(fileStream);
                }
                _context.CMSItems.Add(cmsModel);
                _context.SaveChanges();

                return RedirectToAction("Index");
            }
            else
            return View(model);
        }

        [HttpGet]
        public IActionResult EditPage(int Id)
        {
            CMSItemsViewModel mvm = new CMSItemsViewModel();
            var page = _context.CMSItems.FirstOrDefault(m => m.Id == Id);

            if (page != null)
            {
                mvm.PageName = page.PageName;
                mvm.PageUrl = page.PageUrl;
                mvm.Description = page.Description;
                mvm.BannerImage = page.BannerImage;
            }
            return View(mvm);
        }

        [HttpPost]
        public IActionResult EditPage(CMSItemsViewModel model)
        {
            if (model != null)
            {
                var PageItem = _context.CMSItems.FirstOrDefault(m => m.Id == model.Id);
                if (PageItem != null)
                {
                    PageItem.PageName = model.PageName;
                    PageItem.PageUrl = model.PageUrl;
                    PageItem.Description = model.Description;
                    var BannerImage = PageItem.BannerImage;

                    if (model.BannerImageFile != null)
                    {
                        if (BannerImage != model.BannerImage)
                        {
                            string wwwRootPath = _hostEnvironment.WebRootPath;
                            string fileName = Path.GetFileNameWithoutExtension(model.BannerImageFile.FileName);
                            string extension = Path.GetExtension(model.BannerImageFile.FileName);
                            PageItem.BannerImage = DateTime.Now.ToString("yymmssfff") + extension;


                            string path = Path.Combine(wwwRootPath, "Images", PageItem.BannerImage);
                            //var mem = new MemoryStream();
                            //user.ProfilePicture
                            var fileStream = new FileStream(path, FileMode.Create);
                            model.BannerImageFile.CopyTo(fileStream);
                        }
                        else if (BannerImage == null)
                        {
                            string wwwRootPath = _hostEnvironment.WebRootPath;
                            string fileName = Path.GetFileNameWithoutExtension(model.BannerImageFile.FileName);
                            string extension = Path.GetExtension(model.BannerImageFile.FileName);
                            PageItem.BannerImage = DateTime.Now.ToString("yymmssfff") + extension;


                            string path = Path.Combine(wwwRootPath, "Images", PageItem.BannerImage);
                            //var mem = new MemoryStream();
                            //user.ProfilePicture
                            var fileStream = new FileStream(path, FileMode.Create);
                            model.BannerImageFile.CopyTo(fileStream);
                        }
                    }
                    _context.Entry(PageItem).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
                    _context.SaveChanges();

                    return RedirectToAction("Index");
                }
                return View();
            }
            return View();
        }

        public IActionResult DeletePage(int Id)
        {
            var page = _context.CMSItems.FirstOrDefault(m => m.Id == Id);
            _context.CMSItems.Remove(page)
;
            _context.SaveChanges();

            TempData["successMessage"] = "Page Deleted Successfully.";
            TempData.Keep();

            return RedirectToAction("Index");

        }

        [HttpPost]
        public JsonResult UpdateTransaction(string test)
        {
            OrderDetailViewModel lst = new OrderDetailViewModel();


            return Json(lst);
        }
    }
}

AdminLTE1/Views/CMS/CreatePage.cshtml
@model AdminLTE1.ViewModels.CMSItemsViewModel
@{
    ViewData["Title"] = "CreatePage";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/js/ckeditor/ckeditor.js"></script>
<link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
<environment include="Development">
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
</environment>
<div class="row">
    <!-- left column -->
    <div class="col-md-6">
        <!-- general form elements -->
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">Create Page</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form method="post" enctype="multipart/form-data">
                <div class="card-body">
                    </div>
                    <div class="form-group">
                        <label asp-for="PageName"></label>
                        <input asp-for="PageName" class="form-control" placeholder="Name">
                        <span asp-validation-for="PageName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="PageUrl"></label>
                        <input asp-for="PageUrl" class="form-control" placeholder="Path">
                        <span asp-validation-for="PageUrl" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description"></label>
                        <textarea id="Description" class="ckeditor" name="Description" rows="200"></textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="BannerImageFile"></label>
                        <input asp-for="BannerImageFile" class="form-control" type="file" />
                        <span asp-validation-for="BannerImageFile" class="text-danger"></span>
                    </div>
                <!-- /.card-body -->
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Create</button>
                    <a asp-action="Index" asp-controller="CMS"
                       class="btn btn-primary" style="width:auto">Cancel</a>
                </div>
            </form>
        </div>
    </div>
</div>

AdminLTE1/Views/CMS/EditPage.cshtml
@model AdminLTE1.ViewModels.CMSItemsViewModel
@{
    ViewData["Title"] = "EditPage";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/js/ckeditor/ckeditor.js"></script>
<link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
<div class="row">
    <!-- left column -->
    <div class="col-md-6">
        <!-- general form elements -->
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">Edit Page</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form method="post" enctype="multipart/form-data">
                <div class="card-body">
                    <div asp-validation-summary="All" class="text-danger">
                    </div>
                    <div class="form-group">
                        <label asp-for="PageName"></label>
                        <input asp-for="PageName" class="form-control">
                        <span asp-validation-for="PageName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="PageUrl"></label>
                        <input asp-for="PageUrl" class="form-control">
                        <span asp-validation-for="PageUrl" class="text-danger"></span>
                    </div>
                    <div class="form-group">

                        <label asp-for="Description"></label>
                        <textarea asp-for="Description" id="Description" class="ckeditor" name="Description" rows="200"></textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-group">

                        <label asp-for="BannerImageFile"></label>
                        @if (Model.BannerImage != null)
                        {
                            <img style="width:100px;height:100px; object-fit:cover" src="~/Images/@Model.BannerImage">
                        }
                        <input asp-for="BannerImageFile" class="form-control" type="file" />
                        <span asp-validation-for="BannerImageFile" class="text-danger"></span>
                    </div>
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <button type="submit" asp-controller="CMS" asp-action="Index" class="btn btn-primary">Cancel</button>
                </div>
            </form>
        </div>
    </div>
</div>

@section scripts{

    <script>
        $(document).ready(function () {

            //CKEDITOR.replace('#Description');

        }
        )
    </script>
}

AdminLTE1/Views/CMS/Index.cshtml
@model IEnumerable<AdminLTE1.ViewModels.CMSItemsViewModel>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/js/ckeditor/ckeditor.js"></script>
<link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
<h1>Manage Pages</h1>
<div class="input-group" style="float: right; display: block;margin: 10px;">
    <a class="btn btn-danger" asp-controller="CMS" style="float:right" asp-action="CreatePage">Create Page</a>
</div>
<table class="table table-striped" id="MyDataTable">

    <thead>
        <tr>
            <th>Id</th>
            <th>Page Name</th>
            <th>Page Url</th>
            <th>Description</th>
            <th>Banner Image</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var cms in Model)
        {
            <tr>
                <td>@cms.Id</td>
                <td>@cms.PageName</td>
                <td>@cms.PageUrl</td>
                <td>@cms.Description</td>
                <td>
                    @if (cms.BannerImage != null)
                    {
                        <img style="width:350px;height:350px; object-fit:cover" src="~/Images/@cms.BannerImage">
                    }
                </td>
                <td>
                    <a asp-action="EditPage" asp-controller="CMS" asp-route-id="@cms.Id" class="btn btn-primary">Edit</a>
                </td>
                <td>
                    <a class="btn btn-danger" asp-controller="CMS" asp-action="DeletePage" asp-route-id="@cms.Id" onclick="return confirm('Are you sure you want to delete user : @cms.Id')">Delete</a>

                </td>
            </tr>
        }
    </tbody>
</table>
@section scripts{
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.25/af-2.3.7/datatables.min.css" />
    <script src="~/js/CustomScript.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.25/af-2.3.7/datatables.min.js"></script>
    <script>
        $(document).ready(function () {
            $("#MyDataTable").DataTable();
            CKEDITOR.replace('#Description');

            var obj = { transactionId: 'a', transactionStatus: 'b' };
            var abc = JSON.stringify(obj);
            $.ajax({
                url: '/CMS/UpdateTransaction',
                type: 'POST',
                dataType: 'json',
                data: {test:"test"},
                contentType: "application/json; charset=utf-8",
                success: function (result) {
                    alert(result);
                },
                error: function (xhr) {
                    alert('Error: ' + xhr.statusText);
                }
            });

        }

        )
    </script>
}