AdminLTE1/Controllers/RoleController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using AdminLTE1.Helper;
using AdminLTE1.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AdminLTE1.Controllers
{
    [AuthorizeActionFilter]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly AddDbContext _context;
        public RoleController(RoleManager<IdentityRole> roleManager, AddDbContext context)
        {
            _roleManager = roleManager;
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var roles = await _roleManager.Roles.ToListAsync();
            return View(roles);
        }

        [HttpPost]
        public async Task<IActionResult> AddRole(string roleName)
        {
            if (roleName != null)
            {
                await _roleManager.CreateAsync(new IdentityRole(roleName.Trim()));
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> DeleteRole()
        {
            var roles = await _roleManager.Roles.ToListAsync();
            return View(roles);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteRole(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with ID = {id} cannot be found";
                return View("NotFound");
            }
            else
            {
                var permission = _context.MenuPermissions.Where(m => m.RoleId == new Guid(id));
                foreach (var perm in permission)
                {
                    _context.MenuPermissions.Remove(perm);
                }
                var perms = _context.MenuPermissions.FirstOrDefault(m => m.RoleId == new Guid(id));
                _context.MenuPermissions.Remove(perms);
                _context.SaveChanges();
                var result = await _roleManager.DeleteAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
                return View("Index");
            }
        }
    }
}

AdminLTE1/Views/Role/DeleteRole.cshtml
@model List<Microsoft.AspNetCore.Identity.IdentityRole>
@{
    ViewData["Title"] = "ListRole";
}

<h1>All Roles</h1>
<form method="post" asp-action="AddRole" asp-controller="Role">
    <div class="input-group">
        <input name="roleName" class="form-control w-25">
        <span class="input-group-btn">
            <button class="btn btn-info">Add New Role</button>
        </span>
    </div>
</form>
<table class="table table-striped">
    <tbody>
        @foreach (var role in Model)
        {
            <div class="card mb-3">
                <div class="card-header">
                    User ID : @role.Id
                </div>
                <div class="card-body">
                    User ID : @role.Name
                </div>
            </div>
           
            <div class="card-footer">
                <form asp-action="DeleteRole" asp-route-id="@role.Id" method="post">
                    <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete user : @role.Id')">
                        Delete
                    </button>
                </form>

            </div>
        }
    </tbody>
</table>

AdminLTE1/Views/Role/Index.cshtml
@model List<Microsoft.AspNetCore.Identity.IdentityRole>
@{
    ViewData["Title"] = "ListRole";
    //Layout = "~/Views/Shared/AdminLTE/_Layout.cshtml";
}
<h1>Role Manager</h1>
<form method="post" asp-action="AddRole" asp-controller="Role">
    <div class="input-group">
        <input name="roleName" class="form-control w-25">
        <span class="input-group-btn">
            <button class="btn btn-info">Add New Role</button>
        </span>
    </div>
</form>
<table class="table table-striped">
    <tbody>
        @foreach (var role in Model)
        {
            <div class="card mb-3">
                <div class="card-header">
                    User ID : @role.Id
                </div>
                <div class="card-body">
                    User ID : @role.Name
                </div>
            </div>
        }



    </tbody>
</table>